services:
  frontend:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - ALLOWED_ORIGINS=http://localhost:3000
    env_file:
      - .env
    command: ["python", "main.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: bridge 