version: '3.8'
services:
  frontend:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:5001
      - VITE_SUPABASE_URL=${SUPABASE_LOCAL_URL:-http://localhost:54321}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_LOCAL_ANON_KEY}
    networks:
      - breeze-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - IS_LOCAL=true
      - SUPABASE_LOCAL_URL=http://host.docker.internal:54321
      - SUPABASE_LOCAL_ANON_KEY=${SUPABASE_LOCAL_ANON_KEY}
      - ALLOWED_ORIGINS=http://localhost:5173
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - breeze-network

networks:
  breeze-network:
    driver: bridge