services:
  frontend:
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: breeze-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      # This will need to be updated with your EC2's public IP or domain
      - VITE_BACKEND_URL=http://${EC2_PUBLIC_IP}:5001
    networks:
      - breeze-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: breeze-backend:latest
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      # Add CORS settings for EC2
      - ALLOWED_ORIGINS=http://${EC2_PUBLIC_IP}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - breeze-network

networks:
  breeze-network:
    driver: bridge 